name: CI

on:
  push:
    branches: 
      - master

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./buildDockerImage.sh -v 18.4.0 -x
      working-directory: ./OracleDatabase/SingleInstance/dockerfiles
