name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: ./buildDockerImage.sh -v 18.4.0 -x
      working-directory: ./OracleDatabase/SingleInstance/dockerfiles
    - name: Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.MY_GITHUB_TOKEN }}
    - name: Tag and Push Images
      if: ${{ github.ref == 'refs/heads/master' }}
      working-directory: ./OracleDatabase/SingleInstance/dockerfiles
      run: |
        docker tag oracle/database:18.4.0-xe docker.pkg.github.com/makimenko/docker-images/oradb:18.4.0-xe
        docker push docker.pkg.github.com/makimenko/docker-images/oradb:18.4.0-xe
